@extends('layouts.app')

@section('content')
<hgroup>
  <h2>Cookie policy</h2>
  <h3>We have only mandatory <b>technical cookies</b> used by Laravel framework.</h3>
</hgroup>
<ul>
  <li><code>laravel_session</code> Internally Laravel uses it to identify a session instance for a user. This is an essential cookie and cannot be rejected. This cookie is written to help with site security in preventing Cross-Site Request Forgery attacks.</li>
  <li><code>X-XSRF-TOKEN</code> Laravel stores the current CSRF token in an encrypted <a href="https://laravel.com/docs/10.x/csrf">XSRF-TOKEN cookie</a> that is included with each response generated by the framework. You can use the cookie value to set the X-XSRF-TOKEN request header.</li>
</ul>
@endsection
